# Generated by Django 3.2.6 on 2022-02-16 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220216_0656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
